"""
Production FastAPI server.

This is the PRODUCTION entrypoint for running the agent as a scalable,
A2A-compliant microservice.

Run with: uvicorn main:app --reload
Or use: just prod

This server:
1. Serves the A2A agent card at /.well-known/agent.json
2. Exposes the agent via A2A-compliant endpoints (auto-generated by ADK)
3. Provides health check and metadata endpoints
"""

import os
from pathlib import Path

import uvicorn
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from google.generativeai.adk.contrib.fastapi import add_agent_to_app

from agent import agent
from config import settings

# --- 1. Create the FastAPI application ---
app = FastAPI(
    title=settings.yaml.agent.display_name,
    description=settings.yaml.agent.description,
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)


# --- 2. Mount static files for A2A discovery ---
# The A2A protocol requires serving an agent.json file at /.well-known/agent.json
static_dir = Path(__file__).parent / "static"
app.mount(
    "/.well-known",
    StaticFiles(directory=static_dir / ".well-known"),
    name="well-known",
)


# --- 3. Add the ADK agent to the FastAPI app ---
# This single line auto-generates all A2A-compliant endpoints:
# - POST /run (main agent execution)
# - GET /openapi.json (OpenAPI schema)
add_agent_to_app(app, agent)


# --- 4. Add custom endpoints ---


@app.get("/")
def root() -> dict[str, str]:
    """Health check and metadata endpoint."""
    return {
        "status": "ok",
        "agent_name": settings.yaml.agent.name,
        "display_name": settings.yaml.agent.display_name,
        "description": settings.yaml.agent.description,
        "a2a_discovery": "/.well-known/agent.json",
        "docs": "/docs",
    }


@app.get("/health")
def health() -> dict[str, str]:
    """Simple health check endpoint."""
    return {"status": "healthy"}


# --- 5. Main entry point ---
if __name__ == "__main__":
    # Use PORT from environment, default to 8080
    port = int(os.environ.get("PORT", 8080))

    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=port,
        reload=True,
    )

